FROM node:18

# Install Java
RUN apt-get update && \
    apt-get install -y default-jre && \
    apt-get clean

# Install Firebase CLI
RUN npm install -g firebase-tools

WORKDIR /app
COPY . .

# Expose ports for Firebase emulators
EXPOSE 4000 8080 9099 9199

CMD ["firebase", "emulators:start", "--only", "firestore,ui,storage"]
