FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files first for better caching
COPY server/package*.json ./

# Install dependencies
RUN npm install

COPY .env ./
# Copy project files
COPY server ./

# Build TypeScript code
RUN npm run build

# Expose application port
EXPOSE 3001

# Default command to run the Node.js application
CMD ["npm", "start"]
