FROM node:18

RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN npx playwright install-deps

WORKDIR /app

RUN mkdir -p /app/node_modules && chown -R node:node /app

USER node

COPY --chown=node:node mcp-playwright-sse-server/package*.json ./

RUN npm install

COPY --chown=node:node mcp-playwright-sse-server/ ./src/

RUN npx playwright install chromium

EXPOSE 3003

CMD ["npm", "start"]
