FROM denoland/deno:2.2.2

# Set working directory
WORKDIR /app

# Copy project files
COPY deno.json deno.lock ./
COPY server/ ./server/

# Cache Deno dependencies
RUN deno cache --lock=deno.lock server/server.ts

# Expose application port
EXPOSE 3001

# Default command to run your Deno application
CMD ["deno", "run", "--allow-all", "server/server.ts"]
