FROM node:18

# Install Java
RUN apt-get update && \
    apt-get install -y default-jre tini && \
    apt-get clean


# Install Firebase CLI
RUN npm install -g firebase-tools@13.3.0

WORKDIR /app
COPY . .



COPY firebase-entrypoint.sh /usr/local/bin/firebase-entrypoint.sh
RUN chmod +x /usr/local/bin/firebase-entrypoint.sh

# Set tini as entrypoint for proper signal handling
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/firebase-entrypoint.sh"]

# Expose ports for Firebase emulators
EXPOSE 4000 8080 9099 9199

