// Re-export Firebase-related environment variables from config
import {
    FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID,
    USE_FIREBASE_EMULATOR,
    FIREBASE_EMULATOR_HOST,
    FIREBASE_FIRESTORE_EMULATOR_PORT,
    FIREBASE_STORAGE_EMULATOR_PORT,
    FIRESTORE_CACHE_SIZE_MB,
    FIRESTORE_MAX_CONCURRENT_CONNECTIONS,
    FIRESTORE_PERSISTENCE,
    FIRESTORE_MAX_PAYLOAD_SIZE,
    DEBUG,
    OPENAI_MODEL,
    OPENAI_TIMEOUT
} from "../config/env";

export {
    FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID,
    USE_FIREBASE_EMULATOR,
    FIREBASE_EMULATOR_HOST,
    FIREBASE_FIRESTORE_EMULATOR_PORT,
    FIREBASE_STORAGE_EMULATOR_PORT,
    FIRESTORE_CACHE_SIZE_MB,
    FIRESTORE_MAX_CONCURRENT_CONNECTIONS,
    FIRESTORE_PERSISTENCE,
    FIRESTORE_MAX_PAYLOAD_SIZE,
    DEBUG,
    OPENAI_MODEL,
    OPENAI_TIMEOUT
}; 